import { AngelBrokingSvg, AxisSvg, GrowwSvg, HdfcSvg } from "../assets";

export const brokers = [
  {
    id: 'angel-broking',
    name: 'Angel Investor',
    logo: AngelBrokingSvg,
    description: 'India’s most trusted online trading platform',
  },
  {
    id: 'axis-bank',
    name: 'Axis Bank',
    logo: AxisSvg,
    description: 'India’s most trusted online trading platform',
  },
  {
    id: 'groww',
    name: 'Groww',
    logo: GrowwSvg,
    description: 'India’s most trusted online trading platform',
  },
  {
    id: 'hdfc-bank',
    name: 'HDFC Bank',
    logo: HdfcSvg,
    description: 'India’s most trusted online trading platform',
  },
];


export const holdingsMockData = [
  {
    key: '1',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    quantity: 150,
    avgPrice: 145.20,
    currentPrice: 152.30,
    marketValue: 22845,
    unrealizedPL: 1065,
    unrealizedPLPercent: 4.87,
    sector: 'Technology',
    allocation: 23.5,
  },
  {
    key: '2',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    quantity: 80,
    avgPrice: 2650.00,
    currentPrice: 2720.50,
    marketValue: 21764,
    unrealizedPL: 564,
    unrealizedPLPercent: 2.66,
    sector: 'Technology',
    allocation: 22.3,
  },
  {
    key: '3',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    quantity: 120,
    avgPrice: 310.50,
    currentPrice: 305.20,
    marketValue: 18312,
    unrealizedPL: -636,
    unrealizedPLPercent: -1.71,
    sector: 'Technology',
    allocation: 18.8,
  },
  {
    key: '4',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    quantity: 75,
    avgPrice: 180.00,
    currentPrice: 195.40,
    marketValue: 14655,
    unrealizedPL: 1155,
    unrealizedPLPercent: 8.56,
    sector: 'Consumer Discretionary',
    allocation: 15.0,
  },
  {
    key: '5',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    quantity: 60,
    avgPrice: 135.00,
    currentPrice: 142.80,
    marketValue: 8568,
    unrealizedPL: 468,
    unrealizedPLPercent: 5.78,
    sector: 'Consumer Discretionary',
    allocation: 8.8,
  },
  {
    key: '6',
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    quantity: 95,
    avgPrice: 142.75,
    currentPrice: 156.20,
    marketValue: 14839,
    unrealizedPL: 1277.25,
    unrealizedPLPercent: 9.42,
    sector: 'Financial Services',
    allocation: 7.2,
  },
  {
    key: '7',
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    quantity: 110,
    avgPrice: 165.30,
    currentPrice: 158.40,
    marketValue: 17424,
    unrealizedPL: -759,
    unrealizedPLPercent: -4.18,
    sector: 'Healthcare',
    allocation: 6.5,
  },
  {
    key: '8',
    symbol: 'V',
    name: 'Visa Inc.',
    quantity: 65,
    avgPrice: 210.50,
    currentPrice: 228.75,
    marketValue: 14868.75,
    unrealizedPL: 1186.25,
    unrealizedPLPercent: 8.66,
    sector: 'Financial Services',
    allocation: 5.8,
  },
  {
    key: '9',
    symbol: 'PG',
    name: 'Procter & Gamble Co.',
    quantity: 85,
    avgPrice: 145.80,
    currentPrice: 152.30,
    marketValue: 12945.5,
    unrealizedPL: 552.5,
    unrealizedPLPercent: 4.46,
    sector: 'Consumer Staples',
    allocation: 5.2,
  },
  {
    key: '10',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    quantity: 40,
    avgPrice: 420.30,
    currentPrice: 485.90,
    marketValue: 19436,
    unrealizedPL: 2624,
    unrealizedPLPercent: 15.61,
    sector: 'Technology',
    allocation: 4.8,
  },
  {
    key: '11',
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    quantity: 120,
    avgPrice: 98.40,
    currentPrice: 92.75,
    marketValue: 11130,
    unrealizedPL: -678,
    unrealizedPLPercent: -5.74,
    sector: 'Energy',
    allocation: 4.3,
  },
  {
    key: '12',
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    quantity: 70,
    avgPrice: 105.20,
    currentPrice: 112.40,
    marketValue: 7868,
    unrealizedPL: 504,
    unrealizedPLPercent: 6.84,
    sector: 'Communication Services',
    allocation: 3.1,
  },
];
